lop

diff --git a/.github/workflows/playwright-test.yml b/.github/workflows/playwright-test.yml
--- a/.github/workflows/playwright-test.yml
+++ b/.github/workflows/playwright-test.yml
@@ -10,16 +10,10 @@ jobs:
     permissions:
       contents: write
       pull-requests: write
-      pages: write
-      id-token: write
-
-    environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
-
+     
     timeout-minutes: 60
     runs-on: ubuntu-latest
-   
+    continue-on-error: true
     steps:
     - name: checkout repo
       uses: actions/checkout@v4
@@ -56,41 +50,56 @@ jobs:
       run: npx playwright install --with-deps
 
     - name: Run Playwright tests
-      continue-on-error: true
-      run: npx playwright test
-        
-
-    - name: Get the failure count
       id: tests
       run: |
-          export count=$(cat ./playwright-report/result.txt | grep Failed | cut -d ':' -f 2 | td -d ' ') 
-          echo "fail_count=$count" >> "$GITHUB_OUTPUT"
-          echo $count
+        npx playwright test
+         export count=$(cat ./playwright-report/result.txt | grep Failed | cut -d ':' -f 2 | td -d ' ') 
+         echo "fail_count=$count" >> "$GITHUB_OUTPUT"
 
-
-
-    - uses: mshick/add-pr-comment@v2
-      if: always()
-      with: 
-             message-path: |
-               ./playwright-report/result.txt
-             message-failure: |
-               Workflow failed
 
     - name: Setup Pages
-      if: ${{ steps.tests.outputs.fail_count != '0' }}
+      if: ${{ contains(github.ref,'main')}}
       uses: actions/configure-pages@v3  
 
     - name: Upload Artifact
-      if: ${{ steps.tests.outputs.fail_count != '0' }}
+      if: ${{ contains(github.ref,'main')}}
       uses: actions/upload-pages-artifact@v1
       with:
         path: "./playwright-report"
 
-    - name: Deploy to GitHub Pages
-      if: ${{ steps.tests.outputs.fail_count != '0' }}
-      id: deployment
-      uses: actions/deploy-pages@v2
+    - uses: mshick/add-pr-comment@v2
+      if: always()
+      with:
+          message-path: |
+            ./playwright-report/result.txt
+          message-failure: |
+            Workflow failed
 
+    - name: Fail the job if there any failed case
+      if: ${{ steps.tests.outputs.fail_count == '0' }}
+      run : |
+            exit 1
     
-    
+    outputs:
+      fail_count: ${{ steps.tests.outputs.fail_count }}
+
+  deploy:
+    if:  ${{ contains(github.ref,'main') &&  needs.test.outputs.fail_count != '0' }}
+    runs-on: ubuntu-latest
+    needs: test
+
+    permissions: 
+      pages: write
+      id-token: write
+
+    environment:
+        name: github-pages
+        url: ${{ steps.deployment.outputs.page_url }}
+
+    steps:
+          - name: Deploy to GitHub Pages
+            id: deployment
+            uses: actions/deploy-pages@v2
+
+          
+
