check code

diff --git a/.github/workflows/playwright-test.yml b/.github/workflows/playwright-test.yml
--- a/.github/workflows/playwright-test.yml
+++ b/.github/workflows/playwright-test.yml
@@ -10,10 +10,16 @@ jobs:
     permissions:
       contents: write
       pull-requests: write
-     
+      pages: write
+      id-token: write
+
+    environment:
+            name: github-pages
+            url: ${{ steps.deployment.outputs.page_url }}
+
     timeout-minutes: 60
     runs-on: ubuntu-latest
-    continue-on-error: true
+   
     steps:
     - name: checkout repo
       uses: actions/checkout@v4
@@ -51,54 +57,43 @@ jobs:
 
     - name: Run Playwright tests
       continue-on-error: true
+      run: npx playwright test
+        
+
+    - name: Get the failure count
       id: tests
       run: |
-        npx playwright test
-         export count=$(cat ./playwright-report/result.txt | grep Failed | cut -d ':' -f 2 | td -d ' ') 
-         echo "fail_count=$count" >> "$GITHUB_OUTPUT"
+          export count=$(cat ./playwright-report/result.txt | grep Failed | cut -d ':' -f 2 | td -d ' ') 
+          echo "fail_count=$count" >> "$GITHUB_OUTPUT"
+          echo $count
 
+
+    - uses: mshick/add-pr-comment@v2
+      if: always()
+      with: 
+             message-path: |
+               ./playwright-report/result.txt
+             message-failure: |
+               Workflow failed
 
     - name: Setup Pages
-      if: ${{ steps.tests.outputs.fail_count == '0' }}
+      if: ${{ steps.tests.outputs.fail_count != '0' }}
       uses: actions/configure-pages@v3  
 
     - name: Upload Artifact
-      if: ${{ steps.tests.outputs.fail_count == '0' }}
+      if: ${{ steps.tests.outputs.fail_count != '0' }}
       uses: actions/upload-pages-artifact@v1
       with:
         path: "./playwright-report"
 
-    - uses: mshick/add-pr-comment@v2
-      if: always()
-      with:
-          message-path: |
-            ./playwright-report/result.txt
-          message-failure: |
-            Workflow failed
+    - name: Deploy to GitHub Pages
+      if: ${{ steps.tests.outputs.fail_count != '0' }}
+      id: deployment
+      uses: actions/deploy-pages@v2
 
     - name: Fail the job if there any failed case
-      continue-on-error: true
-      if: ${{ steps.tests.outputs.fail_count == '0' }}
+      if: ${{ steps.tests.outputs.fail_count != '0' }}
       run : |
-            echo 1
+            exit 1
     
-    outputs:
-      fail_count: ${{ steps.tests.outputs.fail_count }}
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: test
-    permissions: 
-            pages: write
-            id-token: write
-    environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
-
-    steps:
-            - name: Deploy to GitHub Pages
-              id: deployment
-              uses: actions/deploy-pages@v2
-              env: 
-                output1: ${{ needs.test.outputs.fail_count }} 
-          
+    
