Updated error logic

diff --git a/.github/workflows/playwright-test.yml b/.github/workflows/playwright-test.yml
--- a/.github/workflows/playwright-test.yml
+++ b/.github/workflows/playwright-test.yml
@@ -12,8 +12,8 @@ jobs:
       pull-requests: write
      
     timeout-minutes: 60
-
     runs-on: ubuntu-latest
+    continue-on-error: true
     steps:
     - name: checkout repo
       uses: actions/checkout@v4
@@ -51,7 +51,11 @@ jobs:
 
     - name: Run Playwright tests
       id: tests
-      run: npx playwright test
+      run: |
+        npx playwright test
+         export count=$(cat ./playwright-report/result.txt | grep Failed | cut -d ':' -f 2 | td -d ' ') 
+         echo "fail_count=$count" >> "$GITHUB_OUTPUT"
+
 
     - name: Setup Pages
       if: ${{ contains(github.ref,'main')}}
@@ -71,8 +75,16 @@ jobs:
           message-failure: |
             Workflow failed
 
+    - uses: Fail the job if there any failed case
+      if: ${{ steps.tests.outputs.fail_count == '0' }}
+      run : |
+            exit 1
+    
+    output:
+      fail-count: ${{ steps.tests.outputs.fail_count }}
+
   deploy:
-    if:  ${{ contains(github.ref,'main')}}
+    if:  ${{ contains(github.ref,'main') && needs.test.outputs.fail_count == '0' }}
     runs-on: ubuntu-latest
     needs: test
 
